---
name: AudioFile-Info
version: 1.10
author:
  - 'Dave Cross, E<lt>dave@mag-sol.comE<gt>'
abstract: Perl extension to get info from audio files.
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  YAML: 0
  perl: 5.6.0
provides:
  AudioFile::Info:
    file: lib/AudioFile/Info.pm
    version: 1.09
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
